### ISSUE TITLE
query for which region a buyer pays 

### ISSUE THREAD

**Issue by and189** [Micha854/full_auto_abo_telegram#12]

**Comment by Micha854** [comment]
This is a Feature request, no issue

**Comment by and189** [comment]
tobaem meinte soll ein issue eröffnen dafür xD


Von Outlook<http://aka.ms/weboutlook> gesendet.

________________________________
Von: Micha854 <notifications@github.com>
Gesendet: Donnerstag, 14. Mai 2020 09:57
An: Micha854/full_auto_abo_telegram <full_auto_abo_telegram@noreply.github.com>
Cc: and189 <and1_89@live.de>; Author <author@noreply.github.com>
Betreff: Re: [Micha854/full_auto_abo_telegram] query for which region a buyer pays (#12)


This is a Feature request, no issue
